name: Test Suite
on: [push, pull_request]

jobs:
  test:
    name: Node 14
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ matrix.os }}-${{ matrix.node_version }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ matrix.os }}-${{ matrix.node_version }}-npm-

      - name: Install Dependencies
        run: |
          npm install -g lerna
          lerna bootstrap --no-ci

      - name: Test App
        run: COVERAGE=true lerna run test

      - name: Report Test Coverage
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ github.workspace }}/packages/*/coverage/lcov.info:lcov
